### ISSUE TITLE
Query regarding indexing

### ISSUE THREAD

**Issue by Appster01** [architecture-building-systems/esoreader#4]
Hello,

I am trying to use the esoreader module within DesignBuilder to read the output variables from an eso file and for this case, I am unable to use pandas. Is there a way to access specific items of a variable's data (which is in the form of a list) by using the timeseries as the index (similar to the date_range pandas function, but **without** using pandas?)

I am new to python and all sorts of programming so sincere apologies if my query-asking skills are crap - I am happy to clarify in the comments!

**Comment by daren-thomas** [comment]
Hello @Appster01 I believe the section [Using esoreader without pandas](https://github.com/architecture-building-systems/esoreader#using-esoreader-without-pandas) of the README.md shows you how to do it. From your question, it seems you've already read that and can read the list of values you would like.

So you now want to know how to select a slice of that list, right? Basically, a list can be indexed like so `mylist[12]` to get the 12th element from that list. You can _also_ do `mylist[5:12]` to get a sublist, starting at index `5` and going up to (but not including) `12`.

Your next task for indexing (I'm not quite sure _what_ you're trying to index - a day's worth of data?) would be to figure out, given, say 8760 values in the list, _which_ ones belong to the day you care about. Check the `datetime` module for doing stuff to dates.

Something like:

```
In [17]: (datetime.datetime(1999, 7, 15) - datetime.datetime(1999, 1, 1)).days * 24
Out[17]: 4680
```

Will give you the hours since January 1st, 1999 for the day you're looking for. Play around with this a bit to make sure you're not "off by one".

**Comment by Appster01** [comment]
Hello Daren. Thank you for getting back so promptly!

I have been able to get specific items from the list using the index in these formats - mylist[12] and mylist[5:12]. What I want to do is, for example, get the value on the 12th of December 2012 at 4pm, which I would be able to get using pandas in the following manner: 

hours_in_year = pd.date_range('2012-01-01', '2012-12-31 T23:00', freq='H')
df = eso.to_frame('zone mean air temperature', frequency = 'Hourly', index = hours_in_year)
**x = df.loc['2012-12-12 16:00:00']**

If I were to get such a value without pandas, I wouldn't be able to provide the required year-month-date-time as the index, right?

**Comment by daren-thomas** [comment]
Exactly. You'd have to convert that date to an hour of the year. [This Stackoverflow page describes some ways to do that](https://stackoverflow.com/questions/63577356/get-hour-of-year-from-a-datetime).

**Comment by Appster01** [comment]
Cheers, thanks for that!
